---
apiVersion: v1
kind: List
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      creationTimestamp: null
      name: "eirini-y"
    rules:
    - apiGroups:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: "eirini-y"
      namespace: "default"
    roleRef:
      kind: ClusterRole
      name: "eirini-y"
      apiGroup: rbac.authorization.k8s.io
    subjects:
    - kind: ServiceAccount
      name: "eirini-y"
      namespace: "default"
---
apiVersion: v1
kind: Service
metadata:
  name: eirini-y-service
spec:
  type: LoadBalancer
  selector:
    app: eirini-y
  ports:
  - protocol: TCP
    port: 4545
    targetPort: 4545
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "eirini-y"
---
apiVersion: v1
kind: Pod
metadata:
  name: eirini-y
  labels:
    app: eirini-y
spec:
  serviceAccountName: "eirini-y"
  containers:
   - image: gcr.io/cff-diego-persistence/eirini-y
     name: eirini-y
     #imagePullPolicy: Never
  restartPolicy: Always
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eirini-y
subjects:
- kind: ServiceAccount
  name: eirini-y
roleRef:
  kind: Role
  name: eirini-y
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: eirini-y
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - namespaces
  verbs:
    - '*'
